security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$bYcpTn/Bg4LV25y.YZZpK.m33KD6ch5FaRIwXKw5jRgdNkvzpOZ3a'
                        roles: ROLE_ADMIN

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            http_basic: ~
            logout:
                path: /logout
                target: /login

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /admin
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
