# config/routes.yaml
dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

login:
  path: /login
  controller: App\Controller\LoginController::index

logout:
  path: /logout
  controller: /login