dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

app_login:
  path: /login
  controller: App\Controller\LoginController::index

logout:
  path: /logout
  controller: /login

api_platform:
  resource: '.'
  type: api_platform